### ISSUE TITLE
How to get the actually value in include directories

### ISSUE THREAD

**Issue by Juddd** [WolframResearch/LibraryLinkUtilities#6]
When I configured my project with the **CMakeList.txt**:
```
#CMakeList.txt
cmake_minimum_required(VERSION 3.15.0)

project ("CMakeProject1")

set(LLU_ROOT "D:/test/LibraryLinkUtilities/install")

find_package(LLU NO_MODULE PATH_SUFFIXES LLU)

add_library(${PROJECT_NAME} SHARED ${PROJECT_NAME}.cpp)

target_compile_definitions(${PROJECT_NAME} PUBLIC $<$<CONFIG:Debug>:LLU_LOG_DEBUG>)
target_link_libraries(${PROJECT_NAME} PRIVATE LLU::LLU)
```
I got a **.sln** file used by *visual studio*, but I found the *include directories* is $\color{red}\text{empty}$ in the configuration. After some search by google, I know that the actual *include directories* is integrated into **LLU::LLU**. Is there any way for me to find out those directories contained in my *include directories*?

**Comment by rafal-c** [comment]
Sure, you can ask CMake about this property of the LLU::LLU target:
```cmake
	get_target_property(LLU_INCLUDE_DIR LLU::LLU INTERFACE_INCLUDE_DIRECTORIES)
	message("LLU include directories: ${LLU_INCLUDE_DIR}")
```

**Comment by Juddd** [comment]
@rafal-c Actually I have try your code before ask here, but it just can print one directory:`D:\test\LibraryLinkUtilities\install\include`, but as I know it should include 3 directories like follow:
![image](https://user-images.githubusercontent.com/10048069/188107886-0a41a82d-f5e3-40c8-b332-19630b1ca1aa.png)

**Comment by rafal-c** [comment]
`INTERFACE_INCLUDE_DIRECTORIES` for `LLU::LLU` should only print one directory as it does not include transitive dependencies.

Judging by the attached screenshot, you found a way to discover all the include directories in Visual Studio. Is there anything else I can help you with?

**Comment by Juddd** [comment]
@rafal-c Yes, the 3 include directories in the screenshot took me a whole day to find. So I'd really like to know if CMake can directly print out all the *include directories* need for my current project `"CMakeProject1"`

**Comment by rafal-c** [comment]
Sounds like this is exactly the same problem that you have: https://discourse.cmake.org/t/how-to-find-all-the-include-folders-for-a-target-for-a-static-analyzer/3233

**Comment by Juddd** [comment]
Well I made it:
```
include(CMakePrintHelpers)
get_target_property(LLUDEPENDS LLU::LLU INTERFACE_LINK_LIBRARIES)
cmake_print_properties(TARGETS LLU::LLU ${LLUDEPENDS} PROPERTIES INTERFACE_INCLUDE_DIRECTORIES)
```
![image](https://user-images.githubusercontent.com/10048069/188172346-2f60d90c-0a7d-4ca4-a217-227f10700014.png)
